// Career Journey Intelligence — shapes crossing the server/web boundary.
// A user has a single Career Journey: one best-fit trajectory generated by the AI.
// When every milestone is completed, the journey auto-extends with new milestones
// rather than being replaced. Milestone `status` is AI-inferred at generation time
// but can also be set manually by the user (user wins).

import { z } from "zod";

export type MilestoneStatus = "not_started" | "in_progress" | "completed";

export type JourneyDetailPriority = "high" | "medium" | "low";

export interface CareerJourneySkillGap {
  skill: string;
  whyItMatters: string;
  priority: JourneyDetailPriority;
}

export interface CareerJourneyNextAction {
  title: string;
  description: string;
  timeframe: string;
}

export interface CareerJourneyRisk {
  risk: string;
  mitigation: string;
}

export interface CareerJourneyDetails {
  strategySummary?: string;
  fitReasons: string[];
  skillGaps: CareerJourneySkillGap[];
  nextActions: CareerJourneyNextAction[];
  risks: CareerJourneyRisk[];
  evidence: string[];
  assumptions?: string[];
  tradeoffs?: string[];
  confidenceFactors?: string[];
}

export interface JourneyMilestone {
  order: number;
  title: string;
  description: string;
  whyItMatters?: string;
  successCriteria?: string[];
  proofArtifacts?: string[];
  firstStep?: string;
  status: MilestoneStatus;
  manuallySet?: boolean;
  estimatedMonthsFromNow: number;
  // AI-estimated, USD-only for Phase 2. Real benchmarked data lands in Phase 3.
  salaryBand: { min: number; max: number; currency: "USD" };
  requiredSkills: string[];
  // Present only on the timeline projection (server-computed), not on persisted milestones.
  targetDate?: string; // ISO date string
  daysRemaining?: number; // signed — negative means overdue
}

export interface CareerJourney {
  id: string;
  profileId?: string;
  title: string;
  description: string;
  confidenceScore: number; // 0–1, how achievable given the current profile
  projectedTimelineMonths: number;
  details?: CareerJourneyDetails | null;
  milestones: JourneyMilestone[];
}

const optionalPreferenceText = (max: number) =>
  z.string().trim().max(max, `Keep this under ${max} characters`).default("");

export const journeyGrowthPaceSchema = z.enum(["steady", "accelerated", "exploratory"]).or(z.literal(""));

export const journeyPrioritySchema = z.enum([
  "salary",
  "stability",
  "leadership",
  "autonomy",
  "learning",
  "location",
  "remote",
  "impact",
]);

export const journeyPreferencesSchema = z.object({
  preferredDirection: optionalPreferenceText(800),
  leanToward: optionalPreferenceText(800),
  avoid: optionalPreferenceText(800),
  growthPace: journeyGrowthPaceSchema.default(""),
  priorities: z.array(journeyPrioritySchema).max(5, "Choose up to 5 priorities").default([]),
  hardConstraints: optionalPreferenceText(1_000),
  notes: optionalPreferenceText(1_500),
});

export type JourneyGrowthPace = z.infer<typeof journeyGrowthPaceSchema>;
export type JourneyPriority = z.infer<typeof journeyPrioritySchema>;
export type JourneyPreferences = z.infer<typeof journeyPreferencesSchema>;

export type JourneyDomain = "path" | "skill" | "application";
export type JourneyUrgency = "urgent" | "important" | "later";

export interface JourneyActionItem {
  domain: JourneyDomain;
  urgency: JourneyUrgency;
  title: string;
  subtitle: string;
  daysRemaining: number | null;
  linkTo: string;
}

export interface JourneyActiveProject {
  id: string;
  source: "profile" | "github";
  title: string;
  url: string | null;
  language: string | null;
  topics: string[];
  lastPushedAt: string;
  activityLabel: string;
  linkedMilestoneOrder?: number;
}

export interface JourneySuggestedProject {
  id: string;
  title: string;
  rationale: string;
  targetMilestoneOrder?: number;
  suggestedSkills: string[];
  effort: "small" | "medium" | "large";
  source: "journey" | "github_patterns" | "market";
}

export interface CareerJourneyResponse {
  journey: CareerJourney | null;
  timeline: JourneyMilestone[];
  actionQueue: JourneyActionItem[];
  journeyPreferences?: JourneyPreferences;
  activeProjects?: JourneyActiveProject[];
  suggestedProjects?: JourneySuggestedProject[];
  githubConnected?: boolean;
}
