// Career Journey Intelligence — shapes crossing the server/web boundary.
// A user has a single Career Journey: one best-fit trajectory generated by the AI.
// When every milestone is completed, the journey auto-extends with new milestones
// rather than being replaced. Milestone `status` is AI-inferred at generation time
// but can also be set manually by the user (user wins).

export type MilestoneStatus = "not_started" | "in_progress" | "completed";

export type JourneyDetailPriority = "high" | "medium" | "low";

export interface CareerJourneySkillGap {
  skill: string;
  whyItMatters: string;
  priority: JourneyDetailPriority;
}

export interface CareerJourneyNextAction {
  title: string;
  description: string;
  timeframe: string;
}

export interface CareerJourneyRisk {
  risk: string;
  mitigation: string;
}

export interface CareerJourneyDetails {
  fitReasons: string[];
  skillGaps: CareerJourneySkillGap[];
  nextActions: CareerJourneyNextAction[];
  risks: CareerJourneyRisk[];
  evidence: string[];
}

export interface JourneyMilestone {
  order: number;
  title: string;
  description: string;
  status: MilestoneStatus;
  manuallySet?: boolean;
  estimatedMonthsFromNow: number;
  // AI-estimated, USD-only for Phase 2. Real benchmarked data lands in Phase 3.
  salaryBand: { min: number; max: number; currency: "USD" };
  requiredSkills: string[];
  // Present only on the timeline projection (server-computed), not on persisted milestones.
  targetDate?: string; // ISO date string
  daysRemaining?: number; // signed — negative means overdue
}

export interface CareerJourney {
  id: string;
  profileId?: string;
  title: string;
  description: string;
  confidenceScore: number; // 0–1, how achievable given the current profile
  projectedTimelineMonths: number;
  details?: CareerJourneyDetails | null;
  milestones: JourneyMilestone[];
}

export type JourneyDomain = "path" | "skill" | "application";
export type JourneyUrgency = "urgent" | "important" | "later";

export interface JourneyActionItem {
  domain: JourneyDomain;
  urgency: JourneyUrgency;
  title: string;
  subtitle: string;
  daysRemaining: number | null;
  linkTo: string;
}

export interface CareerJourneyResponse {
  journey: CareerJourney | null;
  timeline: JourneyMilestone[];
  actionQueue: JourneyActionItem[];
}
