"use client";

import { useState } from "react";
import Link from "next/link";
import PageHeader from "@/components/dashboard/page-header";
import { DASHBOARD_PAGE_HELP } from "@/components/dashboard/page-help";
import Greeting from "@/components/dashboard/greeting";
import DailySuggestions from "@/components/dashboard/daily-suggestions";
import InFlight from "@/components/dashboard/in-flight";
import RecentActivity from "@/components/dashboard/recent-activity";
import TopAction from "@/components/dashboard/top-action";
import QuickChatNote from "@/components/dashboard/quick-chat-note";
import JourneyStatusPanel from "@/components/dashboard/career-journey/journey-status-panel";
import { api } from "@/lib/api";
import type { DashboardMetrics } from "@/types/profile";
import type { CareerJourney, JourneyActionItem, ProactiveNudge, RelevanceSummary } from "@kursa/types";

interface DashboardProps {
    user: { name: string; email: string; createdAt: string };
    initialNudges: ProactiveNudge[];
    initialRelevance: RelevanceSummary | null;
    metrics: DashboardMetrics | null;
    topAction: JourneyActionItem | null;
    activeJourney: CareerJourney | null;
}

function buildDigest(
    user: DashboardProps["user"],
    metrics: DashboardMetrics | null,
    topAction: JourneyActionItem | null,
    relevance: RelevanceSummary | null,
    activeJourney: CareerJourney | null,
    nudges: ProactiveNudge[],
): string {
    const week = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
    const lines: string[] = [`# Career Digest`, `Exported ${week}`, ``, `---`, ``];

    if (activeJourney || relevance?.pathAlignmentScore !== null && relevance?.pathAlignmentScore !== undefined) {
        lines.push(`## Active Journey`);
        lines.push(activeJourney ? `- ${activeJourney.title}` : `- ${relevance?.activePathTitle ?? "No active journey"}`);
        if (relevance?.pathAlignmentScore !== null && relevance?.pathAlignmentScore !== undefined) {
            lines.push(`- Alignment: ${relevance.pathAlignmentScore}%`);
        }
        if (activeJourney?.description) lines.push(`- ${activeJourney.description}`);
        lines.push(``);
    }

    if (relevance) {
        lines.push(`## Accomplishments`);
        lines.push(`- ${relevance.winsThisQuarter} win${relevance.winsThisQuarter !== 1 ? "s" : ""} this quarter`);
        if (relevance.checkInStreak > 0) lines.push(`- ${relevance.checkInStreak}-week check-in streak`);
        lines.push(``);
    }

    if (topAction) {
        lines.push(`## Top Action`);
        lines.push(`- [${topAction.urgency}] ${topAction.title}`);
        if (topAction.subtitle) lines.push(topAction.subtitle);
        if (topAction.daysRemaining !== null) lines.push(`Due in ${topAction.daysRemaining} day${topAction.daysRemaining !== 1 ? "s" : ""}`);
        lines.push(``);
    }

    const skillGaps = activeJourney?.details?.skillGaps ?? [];
    if (skillGaps.length > 0 || (relevance && relevance.staleSkills.length > 0)) {
        lines.push(`## Skills`);
        if (skillGaps.length > 0) {
            lines.push(`### Journey gaps`);
            skillGaps.slice(0, 8).forEach((gap) => lines.push(`- ${gap.skill} (${gap.priority}) — ${gap.whyItMatters}`));
        }
        if (relevance && relevance.staleSkills.length > 0) {
            lines.push(`### Stale skills`);
            relevance.staleSkills.forEach((skill) => lines.push(`- ${skill}`));
        }
        lines.push(``);
    }

    if (metrics?.inFlight && metrics.inFlight.activeCount > 0) {
        lines.push(`## Active Applications (${metrics.inFlight.activeCount})`);
        metrics.inFlight.applications
            .filter((a) => a.stageLabel !== "not aligned")
            .forEach((a) => lines.push(`- ${a.company} — ${a.roleTitle} — ${a.stageLabel}`));
        lines.push(``);
    }

    if (metrics?.recentActivity && metrics.recentActivity.length > 0) {
        lines.push(`## Recent Activity`);
        metrics.recentActivity.forEach((e) => lines.push(`- ${e.label} (${e.timeAgo})`));
        lines.push(``);
    }

    if (nudges.length > 0) {
        lines.push(`## Daily Suggestions`);
        nudges.slice(0, 5).forEach((n) => lines.push(`- ${n.title}: ${n.message}`));
        lines.push(``);
    }

    if (relevance?.recentMemoryFacts?.length) {
        lines.push(`## Memory Facts`);
        relevance.recentMemoryFacts.slice(0, 5).forEach((fact) => lines.push(`- ${fact}`));
        lines.push(``);
    }

    lines.push(`---`);
    lines.push(`Generated by Kursa for ${user.name}`);
    return lines.join("\n");
}

export default function Dashboard({ user, initialNudges, initialRelevance, metrics, topAction, activeJourney }: DashboardProps) {
    const [exporting, setExporting] = useState(false);

    async function handleExport() {
        setExporting(true);
        try {
            const [relevance, proactive] = await Promise.all([
                api.journal.relevance().catch(() => null),
                api.journal.proactive().catch(() => ({ nudges: initialNudges })),
            ]);
            const digest = buildDigest(
                user,
                metrics,
                topAction,
                relevance ?? initialRelevance,
                activeJourney,
                proactive.nudges,
            );
            const blob = new Blob([digest], { type: "text/markdown" });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `kursa-digest-${new Date().toISOString().slice(0, 10)}.md`;
            a.click();
            URL.revokeObjectURL(url);
        } finally {
            setExporting(false);
        }
    }

    return (
        <div className="flex flex-col min-h-full">
            <PageHeader pageTitle="Home" />

            <div className="px-8 pt-6 pb-5 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
                <Greeting user={user} metrics={metrics} help={DASHBOARD_PAGE_HELP.home} />
                <div className="flex items-center gap-2 mt-1.5 self-start sm:self-auto flex-shrink-0">
                    <Link
                        href="/dashboard/journal"
                        className="rounded-md px-3 py-1.5 mono transition-colors text-xs text-accent border border-line bg-bg hover:bg-surface"
                    >
                        log a win →
                    </Link>
                    <button
                        onClick={() => void handleExport()}
                        disabled={exporting}
                        className="rounded-md px-3 py-1.5 mono transition-colors text-xs text-mute border border-line bg-bg cursor-pointer disabled:opacity-50"
                    >
                        {exporting ? "exporting…" : "export career digest"}
                    </button>
                </div>
            </div>

            <div className="px-8 pb-8 grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-5 flex-1">
                <div className="flex flex-col gap-4">
                    {topAction && <TopAction item={topAction} />}

                    <JourneyStatusPanel data={initialRelevance} />

                    <QuickChatNote />

                    <div className="rounded-lg p-4 border border-line bg-surface">
                        <DailySuggestions nudges={initialNudges} />
                    </div>
                </div>

                <div className="flex flex-col gap-4">
                    <div className="rounded-lg p-4 border border-line bg-surface">
                        <InFlight metrics={metrics} />
                    </div>

                    <div className="rounded-lg p-4 border border-line bg-surface">
                        <RecentActivity metrics={metrics} />
                    </div>
                </div>
            </div>
        </div>
    );
}
