name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          DATABASE_URL: postgresql://dummy:dummy@localhost:5432/dummy

      - name: Type Check
        run: pnpm turbo check-types
        
      - name: Build
        run: pnpm turbo build
